name: Region
version: 1.0-SNAPSHOT
main: it.renvins.region.RegionPlugin
api-version: 1.20
authors: [renvins]
description: A plugin to create and manage regions, only whitelisted users can interact in the region
commands:
  region:
    description: "Used to manage regions in the server"